server:
  port: 8094

spring:
  application:
    name: triage-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/triage_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          physical-strategy: com.microservice.triage.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:ayllucare}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    compatibility-verifier:
      enabled: false
    function:
      definition: anamnesisSummaryCreated;triageEvaluationCompleted
    stream:
      bindings:
        anamnesisSummaryCreated-in-0:
          destination: anamnesis-events
          group: triage-service
          content-type: application/json
          binder: rabbit
        triageEvaluationCompleted-out-0:
          destination: triage-events
          content-type: application/json
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: ${RABBITMQ_USER:ayllucare}
                password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: triage-service

authorization:
  jwt:
    secret: ${JWT_SECRET:WriteHereYourSecretStringForTokenSigningCredentials}
    expiration:
      days: 7

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      rabbit:
        binder:
          connection-timeout: 30000
          requested-heartbeat: 30
      binders:
        rabbit:
          environment:
            spring:
              rabbitmq:
                connection-timeout: 30000
                requested-heartbeat: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    rabbit:
      enabled: true

